[www]
user  = www-data
group = www-data

; Écoute sur TCP (plus simple que socket pour Nginx dans le même container)
listen = 127.0.0.1:9000

; Nombre de workers
pm                   = dynamic
pm.max_children      = 10
pm.start_servers     = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests      = 500

; Logs vers stderr
php_admin_value[error_log]  = /dev/stderr
php_admin_flag[log_errors]  = on

; Timeout
request_terminate_timeout = 120